itgalaxy/favicons

- index.js
Changed appleTouch to appleIcon because otherwise the appleIcon option doesn't do anything
> Fixed appleIcon option not working

- index.js
[unzip](https://github.com/EvanOxfeld/node-unzip) is not so well-behaved. It typically emits a `close` event when it's done, but there are [reports](https://github.com/EvanOxfeld/node-unzip/issues/21) that sometimes it doesn't, and that sometimes it emits `end` instead. Monkeypatch `emit()` on the `unzip.Parse` object so that it emits just one `end` event from any combination of `close` and `end` events.
This should answer the concerns at haydenbleasel/gulp-favicons#6.
> monkeypatch unzip.Parse.emit() to emit single 'end'

- index.js
> checks for 2xx codes and sends original error message

- bin/favicons.js
- package.json
- readme.md
Add cli access via minimist which takes argument flags and passes them
in as the config object.
> Add command-line access

- readme.md
Just to avoid confusion: it was throwing `TypeError: Cannot read property 'status' of null`
> Add error check in readme example (callback)

- helpers-es5.js
- helpers.js
https://github.com/haydenbleasel/favicons/issues/90
> Fix backslashes in browserconfig.xml on Windows

- helpers-es5.js
- helpers.js
Fix bug https://github.com/haydenbleasel/favicons/issues/103
> Fix backslashes replace to absolute path

- config/icons.json
- index.js
- package.json
- readme.md
Close https://github.com/haydenbleasel/favicons/issues/134
/cc @haydenbleasel
> Changed: better generation `favicon.ico`.

- config/files.json
- config/icons.json
- test/rfg.html
Close: https://github.com/RealFaviconGenerator/realfavicongenerator/issues/228.
Close: https://github.com/RealFaviconGenerator/realfavicongenerator/issues/234.
/cc @haydenbleasel
> Add new icons size and fix problem with `manifest.json`

- config/html.json
Close: https://github.com/RealFaviconGenerator/realfavicongenerator/issues/230.
Close: https://github.com/RealFaviconGenerator/realfavicongenerator/issues/135.
Sorry for several PR, need time to examination of all issues. This is last on today :smile: 
/cc @haydenbleasel
> Remove unused google tv icon and right order.

- package.json
> Update license field in package.json

- appveyor.yml
> Setup Appveyor CI

- package-lock.json
- package.json
See brunocodutra/webapp-webpack-plugin#72
> Fix broken run-time dependency

- readme.md
as requested in https://github.com/itgalaxy/favicons/pull/232
> Update readme with link to gulp-plugin

- src/helpers.js
- src/index.js
- test/helpers.test.js
> Do not rely on name to detect HTML file

- gulpfile.js
- package-lock.json
- package.json
Before a new release is created, delete all the old release files first because some files could need to be deleted from the final release.
Fix #268
> Clean the "dist" folder before building a new release

- package-lock.json
- package.json
> Bump to v5.4.1

- src/index.ts
> Make index.ts a proper ES module

- package-lock.json
- package.json
- src/index.ts
As discussed in #375 
Pros:
- one dependency less
- TypeScript friendly
Cons:
- code is more obscure
> Replace lodash.defaultsdeep with ES spread operator

- .babelrc
change was done in: https://github.com/itgalaxy/favicons/commit/a5f56a6641b83cf73b3993524e3be90a5ceaca0b
> fix: require min node 14

- readme.md
I was a little confused in my case, so I modified it.
I have been using it. Thank you.
> Correct a mistake in the sample code on README

- src/helpers.ts
- src/index.ts
Mixture of strings and Buffers is allowed
> Correct source type

- src/platforms/windows.ts
> Ensure that background is specified when Windows icon is generated

- readme.md
- src/config/defaults.ts
- src/platforms/android.ts
- src/platforms/appleIcon.ts
- src/platforms/appleStartup.ts
- src/platforms/base.ts
- src/platforms/favicons.ts
- src/platforms/windows.ts
- src/platforms/yandex.ts
- test/__snapshots__/cacheBusting.test.js.snap
- test/cacheBusting.test.js
- test/createExamples.js
This pull request implements a `cacheBustingQueryParam` option: a query paramater added to all URLs that acts as a cache busting system.
Related issue: https://github.com/itgalaxy/favicons/issues/419
> Cache busting with `cacheBustingQueryParam` option
