itgalaxy/favicons

index.js, package.json, test.js
The exported object is still the familiar `favicons()` function. However, this function now has some properties: `setConfig()`, `generateFavicons()`, and `generateFaviconStream()`. The first two were basically present inside `index.js` before, but now we can `require()` them from elsewhere. `generateFaviconStream()` is the streaming interface that was previously hidden inside `generateFavicons()`, split out so stream-aware tools like [gulp](http://gulpjs.com/) can use it. The original test still works, now there's another test for `setConfig()` and `generateFaviconStream()`.
The code for `setConfig()` is kind of a mess, since I had to pull in other stuff that was scattered all over the place. Someone with a firmer vision for `favicons` options could improve this.
:smile: This is yet …
=> Expose stream and config

index.js
No longer chokes when getting `options` without `files`.
=> getConfig() now handles missing options.files

index.js
Fix bug where, if you weren't generating all icon formats, you couldn't use a multiple sources configuration. Without this would get the error `TypeError: Cannot set property 'master_picture' of undefined`
=> Fix multi source config

data/icons.json
The size of the `apple-touch-icon.png` is a classic.
The resolution of the Windows tiles is trickier, see https://realfavicongenerator.net/faq#windows_8_tile_dimensions
=> Minor fixes in icon resolution

helpers.js
Was receiving:
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
And noticed that the rest client was being rebuilt on every request.
This fix will create the rest client once.
Significantly sped up whole process.
=> Optimize and fix REST requests

helpers.js
When using on windows, the generated url contains a backslash.
=> Fixed url in html

helpers.js
I'm sure there's a better way to write this. Updating .includes to indexOf gives a correct match or not for the twitter / og values.
Also, it looks like the `absolute(value)` and `relative(value)` are the same anyway as noted [here](https://github.com/haydenbleasel/favicons/blob/master/helpers.js#L38-L44), so is [this condition](https://github.com/haydenbleasel/favicons/blob/master/helpers.js#L113) even necessary?
```javascript
function relative(directory) {
return url.resolve(options.path, directory);
}
function absolute(directory) {
return url.resolve(options.path, directory);
}
```
=> Resolving error on .includes function

index.js, readme.md
Expose config so consumers of the module can programmatically get a list of files generated without having to read the `config/icons.json` file themselves.
Wanted for https://github.com/davewasmer/ember-cli-favicon/issues/5.
If you prefer, we can expose a deep clone of the config, so that modification isn't possible - though for that, we might want to upgrade from `underscore` to `lodash`.
If you're open to it, I want to go even further and expose a flattened list of files, e.g.:
```js
modules.exports.files = ['favicon.png'].concat(_(config.icons).map(function (icon) {
return Object.keys(icon);
}).flatten().value());
```
Let me know and I can add that to this PR before you merge.
=> Expose config.

index.js, package.json
Unexpected results are occurring when `favicons()` is called multiple times with certain configurations. In my case, when `path` is different.
The unexpected result is that when "files" (manifest.json, browserconfig.xml, etc.) are being created the paths (i.e. `"path/android-chrome-36x36.png"`) are incorrect for any `favicons()` call that's made after already calling `favicons()`.
```js
// Forget the fact that favicons() is asynchronous in this example.
favicons('./favicon.png', {
path: '/one'
});
// File path inside the created manifest.json:
// "\\one\\android-chrome-36x36.png"
// CORRECT
favicons('./favicon.png', {
path: '/two'
});
// File path inside the created manifest.json:
// "\\two\\one\\android-chrome-36x36.png"
// INCORRECT - "\\one" was included in the path
```
This is …
=> Fixed issue with multiple calls to favicons()

index.js
Adds a way to get the generated HTML code (meta tags). The stream function is now taking an optional callback as a second argument. It is NOT mutually exclusive with the `html` option: if the `html` option is given it will still write the tags in the given file path. (BTW @haydenbleasel are you happy with this last bit?)
https://github.com/haydenbleasel/favicons/issues/83
=> Allow the stream API to accept a callback for html

config/files.json, helpers-es5.js
Add short_name in the manifest.json, required to display a web app install banner.
https://developers.google.com/web/fundamentals/engage-and-retain/simplified-app-installs/web-app-install-banners
=> Support web app install banner

readme.md
We should return any pipelines we construct, so that the task doesn't finish until the pipeline finishes.
See https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulptaskname--deps-fn for more info:
"Note: Are your tasks running before the dependencies are complete? Make sure your dependency tasks are correctly using the async run hints: take in a callback or return a promise or event stream."
=> Fix README example for Gulp.

index.js, package.json, readme.md, test/gulpfile.js, test/stream.html
- Simplify all our no-op callbacks.
- Favicon streams' processDocuments was calling the outer callback per-html-file, when that should wait until after all html files are processed.
- If someone passes a second function arg to stream(), we should still call the inner waterfall callback to ensure flow finishes and the stream can complete.
- The main favicons' error handling tried to construct a dict to represent the error, but constructed it in a way that actua
lly dropped the error message itself. We just return the raw error string now, as there's no real point to the dict AFAICT.
- The main favicons' code was attempting to access response.images (and other props), even when there was an error and response was empty, resulting in an inability to propagate the error up due to a new error …
=> Fix (and simplify) error handling/callbacks

config/defaults.json, es5.js, gulpfile.js, helpers-es5.js, helpers.js, index.js, package.json, readme.md
As already explained in my issue 2 days ago, I wanted an option to pipe HTML in `gulp-favicons` for further transformations (in my case, to `jade`). A sample of what I accomplished is: 
```javascript
return gulp.src(['client/img/icon.svg'])
.pipe(svg2png())
.pipe(favicons({
...
html: '../views/favicon.html',
pipeHTML: true,
...
}))
.pipe(gulpif(/views\/favicon.html$/, html2jade()))
.pipe(gulp.dest("public"));
```
This way, you can choose to pipe the generated html file through `html2jade` and save in it `public/../views/favicon.jade`.
As a bonus, I introduced a gulp file to automate es5 scripts generation :D
Highly appreciate it if you publish these updates to the `gulp-favicons` repository too.
Thanks!
=> Add gulp script and pipeHTML options

es5.js
Fixes an error when requiring `gulp-favicons/es5`, where the (es6) index of `favicons` is required instead, breaking es5 environments.
=> Require favicons/es5 in gulp branch es5.js

helpers-es5.js, helpers.js, index.js, readme.md
Source:
Before:
After:
After with offset:
Now you can set offset (in percents) in config, example:
```js
let config = {
background: "#0030d9",
logging: true, 
online: false,
icons: {
android:      false, // Create Android homescreen icon. `boolean`
appleIcon:    { offset: 30 }, // Create Apple touch icons. `boolean`
appleStartup: false, // Create Apple startup images. `boolean`
firefox:      false, // Create Firefox OS icons. `boolean`
windows:      false, // Create Windows 8 tile icons. `boolean`
coast:        { offset: 30 },  // Create Opera Coast icon. `boolean`
favicons:     true,  // Create regular favicons. `boolean`
yandex:       true   // Create Yandex browser icon. `boolean`
}
};
```
=> contain icon, offset feature

config/icons.json
Ref: https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/#//apple_ref/doc/uid/TP40006556-CH27-SW2.
=> Added: `iPad Pro` icon.

config/defaults.json, config/platform-options.json, config/rfg.json, es5.js, helpers-es5.js, helpers.js, index.js, package.json, readme.md
In documentation we can see: 
> or array of `{ size: filepath }`
but according to the code it should be map, not array:
```js
{ [size]: [filepath] }
```
Now source can be array of paths. And better to use `sizeOf` function instead of:
```
sourceset.push({
size: { width: size, height: size, type: 'png' },
file: buffer
});
```
Overlay should be behind main icon.
Icon from RFG:
Before (without offset):
After (with offset):
Before:
```js
html: [ '<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">\n<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">\n<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">\n<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">\n<link rel="apple-touch-icon" …
```
=> Some fixes, some mods

package.json
Recent builds of favicons breaks because of an implied need for Node 6+.
Removing the requirement for Node 6+ by:
Locking down svg2png dependency to patch releases only of 3.0.x. This is done since svg2png 3.1.x+ requires node 6+ (https://github.com/domenic/svg2png/releases).
=> Fix node version requirement

package.json
`to-ico` prior 1.1.2 can generates `.ico` file that are not usable by Chrome and FF, cf #155.
I bumped `to-ico` version to 1.1.2 to get the changes made upstream. You can get more context here: https://github.com/kevva/to-ico/issues/8
=> Fix malformed favicons

helpers-es5.js
The online favicons service is returning valid content-type headers (maybe a recent change, though it's sometime in the last few months), which is causing node-rest-client to convert the raw json buffer into an actual JS object. This then breaks `new Buffer()`, which expects something that `must start with number, buffer, array or string`.
This changes fixes that to re-json and re-xml files based on their extensions. (Otherwise it involvex more drastic changes/fixes to node-rest-client and its horrible API)
=> Fix json/xml file handling from the favicon service

config/files.json
Currently the three largest ones are fetched from the root folder, instead of the same folder where the manifest (and the icons) are created.
=> Use relative URLs for all android icons

readme.md, src/config/defaults.json, src/helpers.js, test/meta.test.js
This will help prevent the error when `name` field is longer than 12 characters, causing `short_name` to be too long.
```
The short_name will be truncated on the homescreen
Failure: Manifest's `short_name` is too long (>12 characters) to be displayed on a homescreen without truncation.
```
=> Add option for 'short_name' in manifest.json

readme.md
Just me being very nitpicking about the gulp usage of this module in the README file. 😄 
In short: `gulp-util` has been deprecated and separated into smaller modules.
The example in the README uses only the `gulp-util.log` submodule which is now under the `fancy-log` module, so I think it should be better to use it instead of relying on the old `gulp-util` (which I guess won't be maintained anymore officially).
For more info: https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
=> Updated README.md according to gulp-util deprecation

package-lock.json, readme.md, src/helpers.js, src/index.js, test/restrict.test.js, test/util.js
Add the ability to specify the exhaustive list of icons to generate per platform
=> feat: Granularity in icons options

src/config/defaults.ts, src/platforms/android.ts, src/platforms/firefox.ts, src/platforms/windows.ts, src/platforms/yandex.ts, test/manifest.test.js
Addresses #354 and #280.
This change looks big, but actually functions which generate manifests/configs were just moved inside corresponding platform classes.
=> Allow to rename files (manifests)

src/platforms/android.ts, test/__snapshots__/array.test.js.snap, test/__snapshots__/background.test.js.snap, test/__snapshots__/default.test.js.snap, test/__snapshots__/loadManifestWithCredentials.test.js.snap, test/__snapshots__/manifestMaskable.test.js.snap, test/__snapshots__/manifestRelativePaths.test.js.snap, test/__snapshots__/meta.test.js.snap, test/__snapshots__/offset.test.js.snap, test/__snapshots__/pixelart.test.js.snap, test/__snapshots__/prefixed.test.js.snap, test/__snapshots__/stream.test.js.snap, test/__snapshots__/svg.test.js.snap, test/manifest.test.js
It seems `.webmanifest` is a preferable extension these days.
It was reported in #280 and https://github.com/jantimon/favicons-webpack-plugin/issues/272
=> Rename manifest.json to manifest.webmanifest

src/helpers.ts, src/svgtool.ts
=> Fix scaling of SVG

src/platforms/favicons.ts, test/__snapshots__/array.test.js.snap, test/__snapshots__/background.test.js.snap, test/__snapshots__/default.test.js.snap, test/__snapshots__/manifestMaskable.test.js.snap, test/__snapshots__/meta.test.js.snap, test/__snapshots__/offset.test.js.snap, test/__snapshots__/pixelart.test.js.snap, test/__snapshots__/prefixed.test.js.snap, test/__snapshots__/svg.test.js.snap
shortcut is used by IE6 which is dead and not supported anymore by most new frameworks and projects
=> fix: remove non standard rel=shortcut

readme.md
I have enhanced the `readme.md` file:
- Added a complete example of usage.
- Removed useless headings.
Derived from PR https://github.com/itgalaxy/favicons/pull/418 and its related comment https://github.com/itgalaxy/favicons/pull/418#discussion_r1101257342.
See [the `readme.md`  file of my fork](https://github.com/Elysiome/favicons#favicons:~:text=Below%20you%20will%20find%20a%20simple%20working%20example%20to%20generate%20an%20output) to get an overview.
Below is the working example in action:
I hope this can help.
=> `readme.md`: example to generate the output
